version: '2'


services:
 client:
  build: ./frontend
  ports:
    - '3000:3000'
  depends_on :
    - server

  server:
      build: ./backend
      ports:
        - '4000:4000'
      depends_on :
        - mongo

  mongo :
      image : mongo
      ports :
        - '27017:27017'


  